config/routes.rb
Biblehive::Application.routes.draw do

  get '/profile/:id', to: 'profiles#show', as: :profile

  resources :user_progresses

  resources :chapters

  resources :books

  devise_for :users
  root to:"static_pages#home"

  get "static_pages/home"
  get "static_pages/help"

  

end

app/models/book.rb
class Book < ActiveRecord::Base
	has_many :chapters, foreign_key: "book_no"
	has_many :user_progresses
end

app/models/chapter.rb
class Chapter < ActiveRecord::Base
	belongs_to :book, primary_key: "book_no", foreign_key: "book_no"
	has_many :user_progresses, foreign_key: "chapter_no"
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :first_name, presence: true

  validates :last_name, presence: true
  	

  def full_name
  	first_name + " " + last_name
  end

  has_many :user_progresses

end

app/models/user_progress.rb
class UserProgress < ActiveRecord::Base
	belongs_to :user
	belongs_to :book, primary_key: "book_no", foreign_key: "book_no"
	belongs_to :chapter, primary_key: "chapter_no", foreign_key: "chapter_no"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.

  protect_from_forgery with: :exception

	before_filter :configure_permitted_parameters, if: :devise_controller?
	
  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :first_name
    devise_parameter_sanitizer.for(:sign_up) << :last_name
    devise_parameter_sanitizer.for(:account_update) << :first_name
    devise_parameter_sanitizer.for(:account_update) << :last_name
  end


end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy]

  # GET /books
  # GET /books.json
  def index
    @books = Book.all
  end

  # GET /books/1
  # GET /books/1.json
  def show
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books
  # POST /books.json
  def create
    @book = Book.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: 'Book was successfully created.' }
        format.json { render action: 'show', status: :created, location: @book }
      else
        format.html { render action: 'new' }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1
  # PATCH/PUT /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: 'Book was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def book_params
      params.require(:book).permit(:book_no, :book_name, :book_chapters)
    end
end

app/controllers/chapters_controller.rb
class ChaptersController < ApplicationController
  before_action :set_chapter, only: [:show, :edit, :update, :destroy]

  # GET /chapters
  # GET /chapters.json
  def index
    @chapters = Chapter.all
  end

  # GET /chapters/1
  # GET /chapters/1.json
  def show
  end

  # GET /chapters/new
  def new
    @chapter = Chapter.new
  end

  # GET /chapters/1/edit
  def edit
  end

  # POST /chapters
  # POST /chapters.json
  def create
    @chapter = Chapter.new(chapter_params)

    respond_to do |format|
      if @chapter.save
        format.html { redirect_to @chapter, notice: 'Chapter was successfully created.' }
        format.json { render action: 'show', status: :created, location: @chapter }
      else
        format.html { render action: 'new' }
        format.json { render json: @chapter.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /chapters/1
  # PATCH/PUT /chapters/1.json
  def update
    respond_to do |format|
      if @chapter.update(chapter_params)
        format.html { redirect_to @chapter, notice: 'Chapter was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @chapter.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /chapters/1
  # DELETE /chapters/1.json
  def destroy
    @chapter.destroy
    respond_to do |format|
      format.html { redirect_to chapters_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_chapter
      @chapter = Chapter.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def chapter_params
      params.require(:chapter).permit(:book_no, :chapter_no, :chapter_verses)
    end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  def show
  	@user = User.find_by_id(params[:id])
  	if @user
  		render action: :show
  	else
  		render file: 'public/404', status: 404, formats: [:html]
  	end
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end
end

app/controllers/user_progresses_controller.rb
class UserProgressesController < ApplicationController
  before_action :set_user_progress, only: [:show, :edit, :update, :destroy]

  # GET /user_progresses
  # GET /user_progresses.json
  def index
    @user_progresses = UserProgress.all
  end

  # GET /user_progresses/1
  # GET /user_progresses/1.json
  def show
  end

  # GET /user_progresses/new
  def new
    @user_progress = UserProgress.new
  end

  # GET /user_progresses/1/edit
  def edit
  end

  # POST /user_progresses
  # POST /user_progresses.json
  def create
    @user_progress = UserProgress.new(user_progress_params)

    respond_to do |format|
      if @user_progress.save
        format.html { redirect_to @user_progress, notice: 'User progress was successfully created.' }
        format.json { render action: 'show', status: :created, location: @user_progress }
      else
        format.html { render action: 'new' }
        format.json { render json: @user_progress.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /user_progresses/1
  # PATCH/PUT /user_progresses/1.json
  def update
    respond_to do |format|
      if @user_progress.update(user_progress_params)
        format.html { redirect_to @user_progress, notice: 'User progress was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user_progress.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_progresses/1
  # DELETE /user_progresses/1.json
  def destroy
    @user_progress.destroy
    respond_to do |format|
      format.html { redirect_to user_progresses_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user_progress
      @user_progress = UserProgress.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_progress_params
      params.require(:user_progress).permit(:user_id, :book_no, :chapter_no, :last_read)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/chapters_helper.rb
module ChaptersHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/user_progresses_helper.rb
module UserProgressesHelper
end

app/views/books/_form.html.erb
<%= form_for(@book) do |f| %>
  <% if @book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
      <% @book.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :book_no %><br>
    <%= f.number_field :book_no %>
  </div>
  <div class="field">
    <%= f.label :book_name %><br>
    <%= f.text_field :book_name %>
  </div>
  <div class="field">
    <%= f.label :book_chapters %><br>
    <%= f.number_field :book_chapters %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/books/edit.html.erb
<h1>Editing book</h1>

<%= render 'form' %>

<%= link_to 'Show', @book %> |
<%= link_to 'Back', books_path %>

app/views/books/index.html.erb
<h1>Listing books</h1>

<table>
  <thead>
    <tr>
      <th>Book no</th>
      <th>Book name</th>
      <th>Book chapters</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td><%= book.book_no %></td>
        <td><%= book.book_name %></td>
        <td><%= book.book_chapters %></td>
        <td><%= link_to 'Show', book %></td>
        <td><%= link_to 'Edit', edit_book_path(book) %></td>
        <td><%= link_to 'Destroy', book, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Book', new_book_path %>

app/views/books/new.html.erb
<h1>New book</h1>

<%= render 'form' %>

<%= link_to 'Back', books_path %>

app/views/books/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Book no:</strong>
  <%= @book.book_no %>
</p>

<p>
  <strong>Book name:</strong>
  <%= @book.book_name %>
</p>

<p>
  <strong>Book chapters:</strong>
  <%= @book.book_chapters %>
</p>

<%= link_to 'Edit', edit_book_path(@book) %> |
<%= link_to 'Back', books_path %>

app/views/chapters/_form.html.erb
<%= form_for(@chapter) do |f| %>
  <% if @chapter.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@chapter.errors.count, "error") %> prohibited this chapter from being saved:</h2>

      <ul>
      <% @chapter.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :book_no %><br>
    <%= f.number_field :book_no %>
  </div>
  <div class="field">
    <%= f.label :chapter_no %><br>
    <%= f.number_field :chapter_no %>
  </div>
  <div class="field">
    <%= f.label :chapter_verses %><br>
    <%= f.number_field :chapter_verses %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/chapters/edit.html.erb
<h1>Editing chapter</h1>

<%= render 'form' %>

<%= link_to 'Show', @chapter %> |
<%= link_to 'Back', chapters_path %>

app/views/chapters/index.html.erb
<h1>Listing chapters</h1>

<table>
  <thead>
    <tr>
      <th>Book no</th>
      <th>Chapter no</th>
      <th>Chapter verses</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @chapters.each do |chapter| %>
      <tr>
        <td><%= chapter.book_no %></td>
        <td><%= chapter.chapter_no %></td>
        <td><%= chapter.chapter_verses %></td>
        <td><%= link_to 'Show', chapter %></td>
        <td><%= link_to 'Edit', edit_chapter_path(chapter) %></td>
        <td><%= link_to 'Destroy', chapter, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Chapter', new_chapter_path %>

app/views/chapters/new.html.erb
<h1>New chapter</h1>

<%= render 'form' %>

<%= link_to 'Back', chapters_path %>

app/views/chapters/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Book Name</strong>
	<%= @chapter.book.book_name %>
</p>

<p>
  <strong>Book no:</strong>
  <%= @chapter.book_no %>
</p>

<p>
  <strong>Chapter no:</strong>
  <%= @chapter.chapter_no %>
</p>

<p>
  <strong>Chapter verses:</strong>
  <%= @chapter.chapter_verses %>
</p>

<%= link_to 'Edit', edit_chapter_path(@chapter) %> |
<%= link_to 'Back', chapters_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Biblehive</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="/">BibleHive</a>
  </div>

  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse navbar-ex1-collapse">
    <ul class="nav navbar-nav">
      <li><%= link_to "myProgress", user_progresses_path %></a></li>
    </ul>
       <ul class="nav navbar-nav navbar-right">
      <% if user_signed_in? %>
        <li><%= link_to current_user.full_name, profile_path(current_user.id) %></li> 
      <% else %>
        <li><%= link_to "Sign In", new_user_session_path %></li>
      <% end %>
      <% if user_signed_in? %>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Options <b class="caret"></b></a>
          <ul class="dropdown-menu">
              <li><%= link_to "Edit", edit_user_registration_path %></li>
              <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
          </ul>
        </li>
      <% end %>
    </ul>
  </div><!-- /.navbar-collapse -->
</nav>

<div class="container">

<% if flash[:notice] %>
<div class="alert alert-success alert-dismissable">
  <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
  <%= notice %>
</div>
<% end %>

<% if flash[:alert] %>
<div class="alert alert-danger alert-dismissable">
  <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
  <%= alert %>
</div>
<% end %>

<%= yield %>

</div><!-- /.container -->

</body>
</html>

app/views/profiles/show.html.erb
<div class="page-header">
	<h1>My Profile Page</h1>
</div>

<h3>What I've Been Reading</h3>

<% profile_read = UserProgress.includes(:book,).where(user_id: params[:id]).where("last_read IS NOT NULL").order("last_read DESC").limit(5) %>

<% profile_read.each do |user_progress|%>
	<%= link_to "#{user_progress.book.book_name} #{user_progress.chapter_no}", chapter_path(user_progress.chapter_id) %>
	<p><%= time_ago_in_words(user_progress.last_read) %> ago</p>
<% end %>

app/views/static_pages/help.html.erb
<h1>StaticPages#help</h1>
<p>Find me in app/views/static_pages/help.html.erb</p>

app/views/static_pages/home.html.erb
<div class="page-header">
	<h1>Welcome <%= current_user.first_name %></h1>
</div>

app/views/user_progresses/_form.html.erb
<%= form_for(@user_progress) do |f| %>
  <% if @user_progress.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user_progress.errors.count, "error") %> prohibited this user_progress from being saved:</h2>

      <ul>
      <% @user_progress.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :book_no %><br>
    <%= f.number_field :book_no %>
  </div>
  <div class="field">
    <%= f.label :chapter_no %><br>
    <%= f.number_field :chapter_no %>
  </div>
  <div class="field">
    <%= f.label :last_read %><br>
    <%= f.date_field :last_read %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/user_progresses/edit.html.erb
<h1>Editing user_progress</h1>

<%= render 'form' %>

<%= link_to 'Show', @user_progress %> |
<%= link_to 'Back', user_progresses_path %>

app/views/user_progresses/index.html.erb
<div class="page-header">
  <h1>Your Bible Reading Progress</h1>
</div>


<%= link_to 'New User progress', new_user_progress_path %>

<% books = Book.where(nil).load %>
<%# chapters = Chapter.where(nil).load %>
<% chapters = Chapter.joins("LEFT JOIN 'user_progresses' ON user_progresses.chapter_id = chapters.id AND user_progresses.user_id = #{current_user.id}").select("chapters.*, user_progresses.chapter_id, user_progresses.user_id, user_progresses.last_read").load %>

<% oldbook = books.select { |book| book.book_no <= 39 } %>
<% newbook = books.select { |book| book.book_no >= 40 } %>

<!-- Quick Links -->
<ul id="myTab" class="nav nav-tabs">
  <li><a href="#Old" data-toggle="tab">Old Testament</a></li>
  <li class="active"><a href="#New" data-toggle="tab">New Testament</a></li>
</ul>
<br>


<div id="myTabContent" class="tab-content">
  <!-- Old Testament -->
  <div class="tab-pane fade" id="Old">
    <ul class="book-links">
      <% oldbook.each do |book| %>
        <li><a href="#<%= book.book_name.gsub(/\s+/, "") %>"><%= book.book_name %></a></li>
      <% end %>
    </ul>

  </div>
  <!-- New Testament -->
    <div class="tab-pane fade active in" id="New">
    <ul class="book-links">
      <% newbook.each do |book| %>
        <li><a href="#<%= book.book_name.gsub(/\s+/, "") %>"><%= book.book_name %></a></li>
      <% end %>
    </ul>

  </div>

</div><!-- /myTabContent -->

<!-- Start Books -->

<% user_progresses = UserProgress.where(user_id: current_user.id) %>


<% books.each do |book| %>
  <div class="page-header">
    <h1 id="<%= book.book_name.gsub(/\s+/, "") %>"><%= book.book_name %></h1>
    <a href="#Top">Top</a>
  </div>
  <div class="row">
    <div class="col-md-12">

      <% current_chapter = chapters.select { |chapter| chapter.book_no == book.book_no } %>

      <% current_chapter.each do |chapter| %>

        <% if chapter.last_read != nil %> 
                      <% vartime = ( (chapter.last_read).to_time - Time.now ).to_i / 1.day %>
                    <% elsif %>
                      <% vartime = 1 %>
                    <%end %>
                    <% if vartime == 1 %> 
                      <span class="progress-default"><%= link_to content_tag(:span, chapter.chapter_no), chapter_path(chapter.id) %></span>
                    <% elsif vartime >= -365 %>
                      <span class="progress-green"><%= link_to content_tag(:span, chapter.chapter_no), chapter_path(chapter.id) %></span>
                    <% elsif vartime >= -730 %>
                      <span class="progress-yellow"><%= link_to content_tag(:span, chapter.chapter_no), chapter_path(chapter.id) %></span>         
                    <% elsif vartime >= -1095 %>
                      <span class="progress-orange"><%= link_to content_tag(:span, chapter.chapter_no), chapter_path(chapter.id) %></span> 
                    <% elsif vartime <= -1096 %> 
                      <span class="progress-red"><%= link_to content_tag(:span, chapter.chapter_no), chapter_path(chapter.id) %></span>
                    <% end %>
        
      <% end %> 
    </div>
  </div>
<% end %>

app/views/user_progresses/new.html.erb
<h1>New user_progress</h1>

<%= render 'form' %>

<%= link_to 'Back', user_progresses_path %>

app/views/user_progresses/show.html.erb
<div class="row">
  <div class="col-md-4">
    <h1><%= @user_progress.book.book_name %></h1>

    <div class="progress-default show-page">
      <h1><span><%= @user_progress.chapter_no %><span></h1>
    </div>
  </div>
  <div class="col-md-4">
    <p>"Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."<p>
  </div>
</div>

<%= form_for(@user_progress) do |f| %>
  <% if @user_progress.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user_progress.errors.count, "error") %> prohibited this user_progress from being saved:</h2>

      <ul>
      <% @user_progress.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :book_no %><br>
    <%= f.number_field :book_no %>
  </div>
  <div class="field">
    <%= f.label :chapter_no %><br>
    <%= f.number_field :chapter_no %>
  </div>
  <div class="field">
    <%= f.label :last_read %><br>
    <%= f.date_field :last_read %>
  </div>
  <div class="action">
    <%= f.submit %>
  </div>
<% end %>



<p>
  <strong>Last read:</strong>
  <%= @user_progress.last_read %>
</p>

<%= link_to 'Edit', edit_user_progress_path(@user_progress) %> |
<%= link_to 'Back', user_progresses_path %>


<div class="page-header">
      <h1>Reading Histroy</h1>
    </div>
<div class="row">
  <div class="col-md-12">
    <% UserProgress.where(user_id: current_user.id).where(book_no: @user_progress.book_no).where(chapter_no: @user_progress.chapter_no).each do |user_progress| %>
     <%= user_progress.last_read %>
     <% end %>
  </div>
</div>